-- Connect as the owner user to the target database:
sqlplus owner_user@database/password

-- Check existing DB links for a specific user:
SELECT * FROM all_db_links 
WHERE UPPER(db_link) LIKE '%SOME_PATTERN%' 
  AND UPPER(username) LIKE '%SPECIFIC_USER%';

-- Drop existing DB links:
DROP DATABASE LINK LINK1;
DROP DATABASE LINK LINK2;
DROP DATABASE LINK LINK3;
DROP DATABASE LINK LINK4;

-- Create DB links with new password (replace <new_password> accordingly):

CREATE DATABASE LINK LINK1 
CONNECT TO USERNAME IDENTIFIED BY <new_password>
USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=host1.domain.com)(PORT=port1)))(CONNECT_DATA=(SID=sid1)))';

CREATE DATABASE LINK LINK2 
CONNECT TO USERNAME IDENTIFIED BY <new_password>
USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=host2.domain.com)(PORT=port2)))(CONNECT_DATA=(SID=sid2)))';

CREATE DATABASE LINK LINK3 
CONNECT TO USERNAME IDENTIFIED BY <new_password>
USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=host3.domain.com)(PORT=port3)))(CONNECT_DATA=(SID=sid3)))';

CREATE DATABASE LINK LINK4 
CONNECT TO USERNAME IDENTIFIED BY <new_password>
USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=host4.domain.com)(PORT=port4)))(CONNECT_DATA=(SID=sid4)))';

-- Test DB links:
SELECT SYSDATE FROM DUAL@LINK1;
SELECT SYSDATE FROM DUAL@LINK2;
SELECT SYSDATE FROM DUAL@LINK3;
SELECT SYSDATE FROM DUAL@LINK4;
